### ISSUE TITLE
Replace `elm` variable by `localRuntime` in native code?

### ISSUE THREAD

**Issue by jvoigtlaender** [TheSeamau5/elm-loop#1]
Please follow the new convention, as per the merged https://github.com/elm-lang/core/pull/127, of using `localRuntime` for what is called `elm` in your code.

**Comment by TheSeamau5** [comment]
So, if I understand from your commits, I should replace only the lowercase `elm` variables by `localRuntime`, correct?

**Comment by jvoigtlaender** [comment]
Yes, exactly. The uppercase ones refer to a static global entity. The lowercase ones are a local, possibly dynamically created (during hotswap) entity. And Evan says better distinguishing them throughout helps with reading code when it comes to issues of the Elm Reactor, hotswapping, etc.

**Comment by TheSeamau5** [comment]
Here, it was fixed in this commit: 6feb996751f8d971e2c15dcd770f369e74f7860a

Thanks I'll keep it in mind. Are there any other things I should be aware of? Like, should I be using stuff like `'use strict'`? Are there other conventions that I'm missing?

**Comment by jvoigtlaender** [comment]
The only other convention I am directly aware of (except for indentation style and such syntactic conventions) is making sure that uses of `Signal.constant` and `Native.Signal.input` are properly distinguished even though on the implementation side the former is just aliasing the latter. But these are simply things I stumbled over and asked Evan about. I guess there are other conventions that he has in his head and which are otherwise just expressed by how the runtime code turns out.

**Comment by TheSeamau5** [comment]
Cool, thanks! I'll try to keep it in mind if I have to use Signals. 

In anycase, I tried my best to copy the style of other native libraries out there. In this case my reference was `elm-linear-algebra`.
